### ISSUE TITLE
react-native projects choke on Flow types

### ISSUE THREAD

**Issue by southerneer** [jumpn/utils-graphql#2]
My team uses https://github.com/absinthe-graphql/absinthe-socket in a React Native context. We updated to the latest release on that repo and started getting errors related to the Flow types in this sub-dependency (we use Typescript instead of Flow). What is the best way to strip out/ignore the Flow types introduced [here](https://github.com/jumpn/utils-graphql/blob/master/src/index.js#L3)? Maybe there's a babel transform that should be added as a peer dependency here to prevent such errors in a React Native context?

**Comment by mgtitimoli** [comment]
Hi @southerneer,

You should do exactly as you described but with the only caveat of setting [@babel/preset-flow](https://babeljs.io/docs/en/babel-preset-flow) under a [babel overrides section entry](https://babeljs.io/docs/en/options#overrides) matching this (or other) package that use flow.

**Comment by southerneer** [comment]
Update: this became a moot point with the latest react-native version (0.58.0 as of writing)...probably because [`metro-react-native-babel-preset`](https://github.com/facebook/metro) handles flow types by default (?)
